[build]
  command = "npm install && npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SKIP_ENV_VALIDATION = "true"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"